### ISSUE TITLE
Rule for tabs to be opened in CURRENT group

### ISSUE THREAD

**Issue by Akimkin** [Akimkin/autogroup#3]
Create a rule (or a special group) that allows tab to be opened in currently active tab group.

Original text from https://addons.mozilla.org/ru/firefox/addon/autogroup/reviews/543870/ :
```
I have one request:
would it be possible to have one group in the rules considered as the CURRENT group from where the new URL is opened: it would allow a URL that you use very often to open in the current group?
The configuration I have is:
- one group for work, with a few URLs
- one group for private matters, with just a "*" sweeping rule, matching everything which is not in the other group.
But when I open Gmail or a few other URLs, I just want it to be opened in the current group, whether it is the one for work, or the private one, I don't care. Just the current one.
```

**Comment by Akimkin** [comment]
Implemented in experimental-nogroup branch, to be tested.

**Comment by klint** [comment]
Hello
Thanks for implementing this request (time does not matter, as you said ;) )
I am testing it, so far, so good!
Cheers

**Comment by Akimkin** [comment]
Finally got to complete this :)

Branch experimental-nogroup merged to master.
Version 0.4 now contains this feature and is already available at addons.mozilla.org.
Closing the issue.
